export const projectData = [
  {
    id: 0,
    name: "Steadfast",
    type: "Full Stack MERN Development",
    description:
      "This is a MERN Stack based agency website to manage their employee and recruiters.",
    website: "https://steadfast-ltd.netlify.app/",
    image: "https://i.ibb.co/mz4tByb/Image.png",
    fullImage: "https://i.ibb.co/86fJLJW/Image.png",
    code: "https://github.com/Imtious-coder/Steadfast",
    li1: " 1: Login as a Recruiter or Employee.",
    li2: " 2: Admin Dashboard for recruiter and employee.",
    li3: " 3: Admin Dashboard for recruiter and employee. Firebase Authentication. & Career Page, FAQ, Success Stories page.",
  },
  {
    id: 1,
    name: "Calculator",
    type: "Front-End Development",
    description:
      "This is a Front-End based Calculator. It's fully responsive and smooth.",
    website: "https://dreamy-curran-97dd26.netlify.app/",
    image: "https://i.ibb.co/SnTNcJg/calculator.png",
    fullImage: "https://i.ibb.co/SnTNcJg/calculator.png",
    code: "https://github.com/Imtious-coder/Calculator",
    li1: " 1: Responsive Design",
    li2: " 2: Smooth Functionality",
    li3: " 3: Clean & well commented code.",
  },
  {
    id: 2,
    name: "Note App",
    type: "Front-End Development",
    description:
      "A note taking app by JavaScript. Simply click on the Add+ button to create a note and start editing.",
    website: "https://note-app-bd.netlify.app/",
    image: "https://i.ibb.co/xJmzFr1/NoteP.png",
    fullImage: "https://i.ibb.co/xJmzFr1/NoteP.png",
    code: "https://github.com/Imtious-coder/Note",
    li1: " 1: Add multiple notes.",
    li2: " 2: Select and edit notes.",
    li3: " 3: Get a live preview of Editing.",
    li4: " 4: Clean & well commented code.",
  },
  {
    id: 3,
    name: "Temperature-Finder",
    type: "Most updated temperature",
    description: "Temperature finder website. Search by your country name.",
    website: "https://imtious-coder.github.io/Temperature-Finder/",
    image: "https://i.ibb.co/xm0J5hv/Temperature1.png",
    fullImage: "https://i.ibb.co/xm0J5hv/Temperature1.png",
    code: "https://github.com/Imtious-coder/Temperature-Finder",
    li1: " 1: Search by the Name.",
    li2: " 2: Get the latest temperature.",
    li3: " 3: Most updated result.",
    li4: " 4: Find any country.",
    li5: " 5: Well commented & clean code",
  },
  {
    id: 4,
    name: "Password-Generator",
    type: "Password Generator",
    description:
      "A random password generator. Generate password as user need. ",
    website: "https://imtious-coder.github.io/Password-Generator/",
    image: "https://i.ibb.co/mrs1Wbp/password-P.png",
    fullImage: "https://i.ibb.co/mrs1Wbp/password-P.png",
    code: "https://github.com/Imtious-coder/Password-Generator",
    li1: " 1: Generate a secure password.",
    li2: " 2: Choose letter amount min 1 to max 10.",
    li3: " 3: Uppercase checkbox to include uppercase letter if need.",
    li4: " 4: Lowercase checkbox to include lowercase letter if need.",
    li5: " 5: Symbol checkbox to include symbol if need.",
  },
  {
    id: 5,
    name: "Quiz_App",
    type: "Quiz Functionality",
    description: "A simple quiz app by JavaScript.",
    website: "https://imtious-coder.github.io/Quiz_App/",
    image: "https://i.ibb.co/RjMwv3t/quizP.png",
    fullImage: "https://i.ibb.co/RjMwv3t/quizP.png",
    code: "https://github.com/Imtious-coder/Quiz_App",
    li1: " 1: Quiz functionality.",
    li2: " 2: Five quizzes.",
    li3: " 3: Match me with your job requirement's.",
    li4: " 4: Score showed.",
    li5: " 5: Clean & well commented code.",
  },
  {
    id: 6,
    name: "Amazon_Login_CLone",
    type: "Login system",
    description: "Frontend based fully cloned login system of amazon.",
    website: "https://fir-14da6.web.app/",
    image: "https://i.ibb.co/D93KVCS/Amazon1.png",
    fullImage: "https://i.ibb.co/ZMSTMFY/loginP.png",
    code: "https://github.com/Imtious-coder/amazon_login_system",
    li1: " 1: Login page.",
    li2: " 2: New account creator page.",
    li3: " 3: Puzzle solving.",
    li4: " 4: Mobile verification.",
    li5: " 5: Responsive design.",
  },
  {
    id: 7,
    name: "My_School",
    type: "School management system",
    description:
      "Ongoing full-stack project including all management system for a school.",
    website: "https://myschool-com.web.app/",
    image: "https://i.ibb.co/gDkB5Fy/School1.jpg",
    fullImage: "https://i.ibb.co/wSkLDYd/schoolP.png",
    code: "https://github.com/Imtious-coder/My_School",
    li1: " 1: School Management System.",
    li2: " 2: Teachers description.",
    li3: " 3: All notice.",
    li4: " 4: Students description.",
    li5: " 5: Admin/Teachers can add or remove a notice.",
    li6: " 6: Admin/Teachers are able to update results.",
    li7: " 7: Students can update their description's.",
  },
  {
    id: 8,
    name: "Countdown-Timer",
    type: "Countdown Functionality",
    description:
      "A countdown website with static data. It can count every remaining seconds.",
    website: "https://imtious-coder.github.io/Countdown-Timer/",
    image: "https://i.ibb.co/PW46bVW/countP.png",
    fullImage: "https://i.ibb.co/PW46bVW/countP.png",
    code: "https://github.com/Imtious-coder/Countdown-Timer",
    li1: " 1: Countdown Functionality.",
    li2: " 2: Count: Days, Hours, Minutes, and Seconds.",
    li3: " 3: Responsive User Interface.",
    li4: " 4: Clean coding.",
    li5: " 5: Well commented code.",
  },
  {
    id: 9,
    name: "Crickmus",
    type: "Team selector website.",
    description: "A team selector website by using React.js",
    website: "https://crickmus.netlify.app",
    image: "https://i.ibb.co/vd9XxYt/crickmus-P2.png",
    fullImage: "https://i.ibb.co/8c6JVbP/crickmus-P.png",
    code: "https://github.com/Imtious-coder/Crickmus",
    li1: " 1: Select your team.",
    li2: " 2: Choose anyone.",
    li3: " 3: Selected list on the right.",
    li4: " 4: Fully Responsive design.",
    li5: " 5: Clean & well commented code.",
  },
  {
    id: 10,
    name: "A_Music",
    type: "Front-End Development",
    description:
      "A music lyric finder. You can find any available music lyric on this site.",
    website: "https://imtious-coder.github.io/A_Music/",
    image: "https://i.ibb.co/Sv0wdqn/A-Music.png",
    fullImage: "https://i.ibb.co/Sv0wdqn/A-Music.png",
    code: "https://github.com/Imtious-coder/A_Music",
    li1: " 1: Search any music.",
    li2: " 2: Get many lyric options.",
    li3: " 3: Get the lyric.",
    li4: " 4: Clean & well commented code",
    li5: " 5: SEO friendly coding",
  },
  {
    id: 11,
    name: "ALGONIO",
    type: "PSD to HTML5",
    description: "This is a PSD to HTML website.",
    website: "https://imtious-coder.github.io/ALGONIO/",
    image: "https://i.ibb.co/WDsy45j/algonio-P2.png",
    fullImage: "https://i.ibb.co/1b5mPwW/algonioP.png",
    code: "https://github.com/Imtious-coder/ALGONIO",
    li1: " 1: Responsive Design",
    li2: " 2: Banner, About Us, Our services, Our Process",
    li3: " 3: Why Us section,",
    li4: " 4: Contact Us",
    li5: " 5: Footer.",
  },
  {
    id: 12,
    name: "A_Doctors",
    type: "Front-End Development",
    description: "Doctors appointment taking website by JavaScript(React).",
    website: "https://keen-sinoussi-d5c500.netlify.app/",
    image: "https://i.ibb.co/dKSZ3tX/adoctors-P2.png",
    fullImage: "https://i.ibb.co/VxTDQV3/adoctors-P.png",
    code: "Fixflex",
    li1: " 1: Dentist Appointment taking website.",
    li2: " 2: Choose the service you want.",
    li3: " 3: Pick any flexible date for appointment.",
  },
  {
    id: 13,
    name: "hello_world",
    type: "Front-End Development",
    description:
      "This is a SPA site, where you can find description about any country in the world",
    website: "https://hello-world-website.netlify.app/",
    image: "https://i.ibb.co/mDDbh4b/helloworld-P2.png",
    fullImage: "https://i.ibb.co/3rQQ793/helloworld-P.png",
    code: "https://github.com/Imtious-coder/hello_world",
    li1: " 1: description of every country.",
    li2: " 2: Find any country.",
    li3: " 3: Click to view details.",
    li4: " 4: The most updated description.",
    li5: " 5: Clean & well commented code.",
  },
  {
    id: 14,
    name: "StoreX",
    type: "PSD to HTML",
    description: "A Pixel Perfect fully responsive PSD to HTML site.",
    website: "https://imtious-coder.github.io/Store_X/",
    image: "https://i.ibb.co/ZJv3H5d/StoreX1.jpg",
    fullImage: "https://i.ibb.co/rbYz7Kq/storexP.png",
    code: "https://github.com/Imtious-coder/Store_X",
    li1: " 1: Clean code.",
    li2: " 2: Fully responsive",
    li3: " 3: Well commented",
    li4: " 4: User friendly",
    li5: " 5: Seo friendly coding",
  },
  {
    id: 15,
    name: "A_ShopBD",
    type: "E-commerce Web App",
    description: "Full-stack e-commerce project by React, Node, and MongoDB.",
    website: "https://ema-john-7355e.web.app/",
    image: "https://i.ibb.co/KwfQnpJ/Ashop1.png",
    fullImage: "https://i.ibb.co/fGpDM3d/ashopP.png",
    code: "",
    li1: " 1: ",
    li2: " 2: ",
    li3: " 3: ",
    li4: " 4: ",
    li5: " 5: ",
    li6: " 6: ",
    li7: " 7: ",
  },
];
