export const projectData = [
  {
    id: 0,
    name: "Hiree.io",
    type: "Front-End Development",
    description:
      "Courier Agency Website to manage their Employee and Recruiters.",
    website: "https://hiree-io.netlify.app/",
    image: "https://i.ibb.co/mz4tByb/Image.png",
    fullImage: "https://i.ibb.co/86fJLJW/Image.png",
    code: "https://github.com/Imtious-coder/Hiree.io",
    li1: " 1. Smart hiring system website.",
    li2: " 2. Unlimited functionality with 100% responsiveness and clean code.",
    li3: " 3. Admin dashboard for managing the whole website data.",
  },
  {
    id: 1,
    name: "Market.",
    type: "Full Stack Development. MERN",
    description: "Next level E-commerce website. 📱",
    website: "https://market-web.netlify.app/",
    image: "https://i.ibb.co/SnTNcJg/calculator.png",
    fullImage: "https://i.ibb.co/SnTNcJg/calculator.png",
    admin: "https://market-admin.netlify.app/",
    code: "https://github.com/Imtious-coder/Market_UI",
    server: "https://github.com/Imtious-coder/Market",
    li1: " 1: Next-level e-commerce webapp in MERN Stack.",
    li2: " 2: Unlimited functionality with 100% responsiveness and clean code.",
    li3: " 3: Admin dashboard for managing the whole website data.",
  },
  {
    id: 2,
    name: "Emmi.io",
    type: "PSD to HTML5",
    description:
      "Your Health management website. Fully Responsive and Smooth UI 📱",
    website: "https://imtious-coder.github.io/Emmi.io/",
    image: "https://i.ibb.co/SnTNcJg/calculator.png",
    fullImage: "https://i.ibb.co/SnTNcJg/calculator.png",
    code: "https://github.com/Imtious-coder/Emmi.io",
    li1: " 1: Responsive Design",
    li2: " 2: Smooth Functionality",
    li3: " 3: Clean & well commented code.",
  },
  {
    id: 3,
    name: "Calculate",
    type: "Front-End Development",
    description: "Functionall Calculator. Fully Responsive and Smooth UI 📱",
    website: "https://calculate-imtious.netlify.app",
    image: "https://i.ibb.co/SnTNcJg/calculator.png",
    fullImage: "https://i.ibb.co/SnTNcJg/calculator.png",
    code: "https://github.com/Imtious-coder/Calculate",
    li1: " 1: Responsive Design",
    li2: " 2: Smooth Functionality",
    li3: " 3: Clean & well commented code.",
  },
  // {
  //   id: 2,
  //   name: "Note App",
  //   type: "Front-End Development",
  //   description: "Note Taking Web App. Easy To Use With Live Data Update 📃",
  //   website: "https://note-app-bd.netlify.app/",
  //   image: "https://i.ibb.co/xJmzFr1/NoteP.png",
  //   fullImage: "https://i.ibb.co/xJmzFr1/NoteP.png",
  //   code: "https://github.com/Imtious-coder/Note",
  //   li1: " 1: Add multiple notes.",
  //   li2: " 2: Select and edit notes.",
  //   li3: " 3: Get a live preview of Editing.",
  //   li4: " 4: Clean & well commented code.",
  // },
  // {
  //   id: 4,
  //   name: "Temperature-Finder",
  //   type: "Front-End Development",
  //   description: "Search The Temperature. Type Your Country Name 🥶",
  //   website: "https://imtious-coder.github.io/Temperature-Finder/",
  //   image: "https://i.ibb.co/xm0J5hv/Temperature1.png",
  //   fullImage: "https://i.ibb.co/xm0J5hv/Temperature1.png",
  //   code: "https://github.com/Imtious-coder/Temperature-Finder",
  //   li1: " 1: Search by the Name.",
  //   li2: " 2: Get the latest temperature.",
  //   li3: " 3: Most updated result.",
  //   li4: " 4: Find any country.",
  //   li5: " 5: Well commented & clean code",
  // },
  // {
  //   id: 5,
  //   name: "Password-Generator",
  //   type: "Vanilla JS",
  //   description: "Password Generator. Generates A Random & Unique Password.",
  //   website: "https://imtious-coder.github.io/Password-Generator/",
  //   image: "https://i.ibb.co/mrs1Wbp/password-P.png",
  //   fullImage: "https://i.ibb.co/mrs1Wbp/password-P.png",
  //   code: "https://github.com/Imtious-coder/Password-Generator",
  //   li1: " 1: Generate a secure password.",
  //   li2: " 2: Choose letter amount min 1 to max 10.",
  //   li3: " 3: Uppercase checkbox to include uppercase letter if need.",
  //   li4: " 4: Lowercase checkbox to include lowercase letter if need.",
  //   li5: " 5: Symbol checkbox to include symbol if need.",
  // },
  // {
  //   id: 6,
  //   name: "Quiz_App",
  //   type: "Vanilla JS",
  //   description: "Quiz App. Complete And Get The Score After Finishing 😄",
  //   website: "https://imtious-coder.github.io/Quiz_App/",
  //   image: "https://i.ibb.co/RjMwv3t/quizP.png",
  //   fullImage: "https://i.ibb.co/RjMwv3t/quizP.png",
  //   code: "https://github.com/Imtious-coder/Quiz_App",
  //   li1: " 1: Quiz functionality.",
  //   li2: " 2: Five quizzes.",
  //   li3: " 3: Match me with your job requirement's.",
  //   li4: " 4: Score showed.",
  //   li5: " 5: Clean & well commented code.",
  // },
  // {
  //   id: 6,
  //   name: "Amazon_Login_CLone",
  //   type: "Login system",
  //   description: "Frontend based fully cloned login system of amazon.",
  //   website: "https://fir-14da6.web.app/",
  //   image: "https://i.ibb.co/D93KVCS/Amazon1.png",
  //   fullImage: "https://i.ibb.co/ZMSTMFY/loginP.png",
  //   code: "https://github.com/Imtious-coder/amazon_login_system",
  //   li1: " 1: Login page.",
  //   li2: " 2: New account creator page.",
  //   li3: " 3: Puzzle solving.",
  //   li4: " 4: Mobile verification.",
  //   li5: " 5: Responsive design.",
  // },
  // {
  //   id: 7,
  //   name: "My_School",
  //   type: "School management system",
  //   description:
  //     "Ongoing full-stack project including all management system for a school.",
  //   website: "https://myschool-com.web.app/",
  //   image: "https://i.ibb.co/gDkB5Fy/School1.jpg",
  //   fullImage: "https://i.ibb.co/wSkLDYd/schoolP.png",
  //   code: "https://github.com/Imtious-coder/My_School",
  //   li1: " 1: School Management System.",
  //   li2: " 2: Teachers description.",
  //   li3: " 3: All notice.",
  //   li4: " 4: Students description.",
  //   li5: " 5: Admin/Teachers can add or remove a notice.",
  //   li6: " 6: Admin/Teachers are able to update results.",
  //   li7: " 7: Students can update their description's.",
  // },
  // {
  //   id: 7,
  //   name: "Countdown-Timer",
  //   type: "Vanilla JS",
  //   description:
  //     "Countdown Website With Static Input. Count Every Remaining Seconds ⌚",
  //   website: "https://imtious-coder.github.io/Countdown-Timer/",
  //   image: "https://i.ibb.co/PW46bVW/countP.png",
  //   fullImage: "https://i.ibb.co/PW46bVW/countP.png",
  //   code: "https://github.com/Imtious-coder/Countdown-Timer",
  //   li1: " 1: Countdown Functionality.",
  //   li2: " 2: Count: Days, Hours, Minutes, and Seconds.",
  //   li3: " 3: Responsive User Interface.",
  //   li4: " 4: Clean coding.",
  //   li5: " 5: Well commented code.",
  // },
  // {
  //   id: 9,
  //   name: "Crickmus",
  //   type: "Team selector website.",
  //   description: "A team selector website by using React.js",
  //   website: "https://crickmus.netlify.app",
  //   image: "https://i.ibb.co/vd9XxYt/crickmus-P2.png",
  //   fullImage: "https://i.ibb.co/8c6JVbP/crickmus-P.png",
  //   code: "https://github.com/Imtious-coder/Crickmus",
  //   li1: " 1: Select your team.",
  //   li2: " 2: Choose anyone.",
  //   li3: " 3: Selected list on the right.",
  //   li4: " 4: Fully Responsive design.",
  //   li5: " 5: Clean & well commented code.",
  // },
  // {
  //   id: 8,
  //   name: "Musico.io",
  //   type: "Front-End Development",
  //   description: "Music Lyric Finder. Just Search By The Music Name 🎸",
  //   website: "https://imtious-coder.github.io/A_Music/",
  //   image: "https://i.ibb.co/Sv0wdqn/A-Music.png",
  //   fullImage: "https://i.ibb.co/Sv0wdqn/A-Music.png",
  //   code: "https://github.com/Imtious-coder/A_Music",
  //   li1: " 1: Search any music.",
  //   li2: " 2: Get many lyric options.",
  //   li3: " 3: Get the lyric.",
  //   li4: " 4: Clean & well commented code",
  //   li5: " 5: SEO friendly coding",
  // },
  {
    id: 11,
    name: "Digi.io",
    type: "PSD to HTML5",
    description: "A PSD To HTML5 Website. 100% Responsiveness.",
    website: "https://imtious-coder.github.io/Digi.io/",
    image: "https://i.ibb.co/WDsy45j/algonio-P2.png",
    fullImage: "https://i.ibb.co/1b5mPwW/algonioP.png",
    code: "https://github.com/Imtious-coder/Digi.io",
    li1: " 1: Responsive Design",
    li2: " 2: Banner, About Us, Our services, Our Process",
    li3: " 3: Why Us section,",
    li4: " 4: Contact Us",
    li5: " 5: Footer.",
  },
  // {
  //   id: 12,
  //   name: "A_Doctors",
  //   type: "Front-End Development",
  //   description: "Doctors Appointment Taking Website Using React.js",
  //   website: "https://keen-sinoussi-d5c500.netlify.app/",
  //   image: "https://i.ibb.co/dKSZ3tX/adoctors-P2.png",
  //   fullImage: "https://i.ibb.co/VxTDQV3/adoctors-P.png",
  //   code: "Fixflex",
  //   li1: " 1: Dentist Appointment taking website.",
  //   li2: " 2: Choose the service you want.",
  //   li3: " 3: Pick any flexible date for appointment.",
  // },
  // {
  //   id: 13,
  //   name: "hello_world",
  //   type: "Front-End Development",
  //   description: "Find The Information About Any Country In The World.",
  //   website: "https://hello-world-website.netlify.app/",
  //   image: "https://i.ibb.co/mDDbh4b/helloworld-P2.png",
  //   fullImage: "https://i.ibb.co/3rQQ793/helloworld-P.png",
  //   code: "https://github.com/Imtious-coder/hello_world",
  //   li1: " 1: description of every country.",
  //   li2: " 2: Find any country.",
  //   li3: " 3: Click to view details.",
  //   li4: " 4: The most updated description.",
  //   li5: " 5: Clean & well commented code.",
  // },
  // {
  //   id: 14,
  //   name: "StoreX",
  //   type: "PSD to HTML5",
  //   description: "A Pixel Perfect Fully Responsive PSD To HTML5 Site.",
  //   website: "https://imtious-coder.github.io/Store_X/",
  //   image: "https://i.ibb.co/ZJv3H5d/StoreX1.jpg",
  //   fullImage: "https://i.ibb.co/rbYz7Kq/storexP.png",
  //   code: "https://github.com/Imtious-coder/Store_X",
  //   li1: " 1: Clean code.",
  //   li2: " 2: Fully responsive",
  //   li3: " 3: Well commented",
  //   li4: " 4: User friendly",
  //   li5: " 5: Seo friendly coding",
  // },
  // {
  //   id: 15,
  //   name: "A_ShopBD",
  //   type: "E-commerce Web App",
  //   description: "Full-stack e-commerce project by React, Node, and MongoDB.",
  //   website: "https://ema-john-7355e.web.app/",
  //   image: "https://i.ibb.co/KwfQnpJ/Ashop1.png",
  //   fullImage: "https://i.ibb.co/fGpDM3d/ashopP.png",
  //   code: "",
  //   li1: " 1: ",
  //   li2: " 2: ",
  //   li3: " 3: ",
  //   li4: " 4: ",
  //   li5: " 5: ",
  //   li6: " 6: ",
  //   li7: " 7: ",
  // },
];
